# Generated by Django 2.1 on 2018-09-04 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sihisb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domainvalue',
            old_name='id_domain',
            new_name='id_domain_fk',
        ),
    ]
